apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: r0s671j80-nodejs-gitops
  description: This is GitOps manifest for r0s671j80-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: r0s671j80-nodejs
    janus-idp.io/tekton: r0s671j80-nodejs 
    backstage.io/kubernetes-id: r0s671j80-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:r0s671j80-nodejs
